#! /bin/sh
#
# BSPWM Configuration

# Run system specific startups.
sh $HOME/.scripts/local/init.sh

# Simple X hotkey Daemon init.
sxhkd &

# Set up tags.
bspc monitor -d I II III IV V VI

# Border and gaps settings.
bspc config border_width         2
bspc config window_gap          7

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Rules.
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium-browser desktop='^2' border=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a blueman-manager state=floating
bspc rule -a Firefox border=off

# Universal service startups that are required on all my PC's.
compton &
feh --bg-fill $HOME/Pictures/wallpapers/wallpaper.jpg
dunst &

# Status bar.
sh $HOME/.scripts/polybar_start.sh

