#! /bin/sh
#
# BSPWM Configuration

# Run system specific startups.
sh $HOME/.scripts/local/init.sh

# Simple X hotkey Daemon init.
sxhkd &

# Set up tags.
bspc monitor -d I II III IV V VI

# Border and gaps settings.
bspc config border_width         2
bspc config normal_border_color "#363636"
bspc config focused_border_color "#767676"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#26E2FF"

bspc config top_padding        24
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0

bspc config window_gap          7

bspc config split_ratio          0.5
bspc config auto_alternate true
bspc config auto_cancel true
bspc config initial_polarity first_child

bspc config borderless_monocle   true
bspc config gapless_monocle      false

# Multihead behavior
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Rules.
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium-browser desktop='^2' border=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a blueman-manager state=floating
bspc rule -a Firefox border=off

# Universal service startups that are required on all my PC's.
compton &
dunst &

# Wallpaper
sh $HOME/.scripts/wallpaper.sh

# Status bar.
sh $HOME/.scripts/polybar_start.sh

